### ISSUE TITLE
Reliquary Finding quests

### ISSUE THREAD

**Issue by baileyholl** [Collateral-Damage/Simply-Magic-2#18]
This quest line will be in the very first quest section that gives an overview. Each quest will branch off the main quest taht gives a short explanation as to how reliquary items can be found. Each quest off the main quest is one of the items that is hidden and maybe a brief description about what the item does. Rewards can be a loot bag depending on the rarity of the item.

**Comment by jives99** [comment]
Added Reliquary Item find quests. Done and Uploaded
