### ISSUE TITLE
Nerf Vanilla Armors/Tools past iron

### ISSUE THREAD

**Issue by baileyholl** [Collateral-Damage/Simply-Magic-2#3]

**Comment by baileyholl** [comment]
@BrizzleMFD Whoops, they don't need removed, they need to be reduced to 1 durability if they are above iron, and the iron pickaxe nerfed. if they are removed we will break all of the mod recipes :P

**Comment by BrizzleMFD** [comment]
Right. Forgot about that. Dam recipes

**Comment by baileyholl** [comment]
The old script works just fine, I replaced them and this is complete.
